" is ~/.vim/vimrc"
" ln -sf ~/dotfiles/.vim/vimrc ~/.vim/vimrc
" Reload vimrc with the vim command :so $(PATH)"
"
" Show colors"
syntax on

" Allow copy paste on system clipboard"
" key shortcut is "+y
set clipboard=unnamedplus

" leader key is space"
map <Space> <Leader>

" disable matching bracket highlight"
" let g:loaded_matchparen=1
" matching bracket's color is blue
hi MatchParen ctermfg=grey ctermbg=blue

" NerdTree-like netrw :Vex"
let g:netrw_banner=0 "hide big banner"
let g:netrw_liststyle=3 "tree view"
let g:netrw_browse_split=4 "open the file in the previous window"
let g:netrw_altv=1 "open the file the right"
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide=&wildignore
let g:netrw_list_hide='\(^\|\s\s\)\zs\.\S\+'

" Display line number for the current line"
set number relativenumber
" Display ruler"
set ruler
" Display a column at 80 char"
set cc=80
highlight ColorColumn ctermbg=0

" Smart case-insensitive, if one character or more is in UPPER CASE"
" search becomes case sensitive"
" set ignorecase
" set smartcase

" always show the statusline"
set laststatus=2

" Quick search with :grep <keyword>, then :copen, and :ccl to close quickfix"
set gp=git\ grep\ -n

" Allow mouse"
set mouse=a

" Indentation style"
set autoindent smartindent
filetype indent on
" Tabulation is only n spaces wide"
set tabstop=2
" Indentation corresponds to a single tab, should be equal to tabstop"
set shiftwidth=2
" spaces instead of tab"
"set expandtab

" To open buffers without saving the current file"
set hidden
" No swap files allowed"
set noswapfile

" Search down into subfolders"
" Provides tab completion for all file-related tasks"
" :find *<file>"
set path+=**

" Display all matching files when we tab complete"
"set wildmenu
"set wildmode=list:longest,full
set wildmode=list:longest,list:full
set wildignore+=*/__pycache__/*,*/venv/*,*/dist/*

" In normal mode, show the pressed key in the bottom right hand corner"
set showcmd

" Faster way to switch between buffers"
map <Leader>b :ls<CR>:b<Space>
map <Leader>` :buffer #<cr>
nnoremap te :tabedit<Space>

" From TPA's advanced motions P1, paste register stays unchanged "
xnoremap <Leader>p "_dP

" Place the cursor to the center of the screen for vertical movement and
" searches"
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv

" Split window"
nnoremap so :split<Return><C-w>w
nnoremap se :vsplit<Return><C-w>w
" Resize window"
"nnoremap s<Left> <C-w><
"nnoremap s<Right> <C-w>>
"nnoremap s<Up> <C-w>+
"nnoremap s<Down> <C-w>-

" Move between split windows"
" nnoremap sh <C-w>h
" nnoremap sk <C-w>k
" nnoremap sl <C-w>l
" nnoremap sj <C-w>j

" Maximize window in a new tab"
nnoremap sm :tab split<CR>

" :W and :Q behave like :w and :q respectively "
command! W write
command! Q quit

" Create the tags file (may need to install ctags first)"
command! MakeTags !ctags -R .

" subtitutions made easier"
nnoremap <leader>s :%s/

" snippets"
nnoremap ,html :-1read $HOME/.vim/snippets/.skeleton.html<CR>4jf>a
nnoremap ,lorem :-1read $HOME/.vim/snippets/.lorem.txt<CR>

" Plugins"
" for tpope's commentary"
filetype plugin indent on
