" is ~/.vim/vimrc"
" ln -sf ~/dotfiles/.vim/vimrc ~/.vim/vimrc
" Reload vimrc with the vim command :so $(PATH)"

syntax enable

" auto install vim-plug plugin manager
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins"
try
	call plug#begin()

" List your plugins here
	Plug 'NLKNguyen/papercolor-theme'
	Plug 'tpope/vim-sensible'
	Plug 'tpope/vim-commentary'
	Plug 'tpope/vim-surround'
	Plug 'yegappan/lsp'
	Plug 'mattn/emmet-vim'

	call plug#end()

" enable yegappan lsp"
	packadd lsp

catch
endtry

set background=light
set t_Co=256
try 
	colorscheme PaperColor
catch
	try 
		colorscheme gruvbox
	catch
		try
			colorscheme morning
		catch
		endtry
	endtry
endtry


" Allow copy paste on system clipboard"
" old method: key shortcut is "+y
set clipboard=unnamedplus

" leader key is space"
map <Space> <Leader>

" In normal mode, show the pressed key in the bottom right hand corner"
set showcmd

" matching bracket's color is blue
hi MatchParen ctermfg=grey ctermbg=blue

" NerdTree-like netrw :Vex"
let g:netrw_banner=0 "hide big banner"
let g:netrw_liststyle=3 "tree view"
let g:netrw_browse_split=4 "open the file in the previous window"
let g:netrw_altv=1 "open the file the right"
let g:netrw_keepdir = 0 "sync current dir and browsing dir"
let g:netrw_list_hide=&wildignore
let g:netrw_list_hide='\(^\|\s\s\)\zs\.\S\+'

" Display line number for the current line"
set number relativenumber
set ruler

" Display a column at 80 char"
set cc=80
highlight ColorColumn ctermbg=7

" always show the statusline, useful for filenames"
set laststatus=2
set statusline=%<[%n]%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P

" Quick search with :grep <keyword>, then :copen, and :ccl to close quickfix"
set gp=git\ grep\ -n

" Allow mouse"
set mouse=a belloff=all

" Indentation style"
filetype plugin indent on
" Tabulation is only n spaces wide ; shiftwidth should be equal to tabstop"
set tabstop=4 shiftwidth=4

"autocmd FileType javascript setlocal shiftwidth=4 tabstop=4
"autocmd FileType html setlocal shiftwidth=2 tabstop=2

" To open buffers without saving the current file"
set hidden
" No swap files allowed"
set noswapfile

" Provides tab completion for all file-related tasks"
" :find *<file>"
set path=.,,**

" Display all matching files when we tab complete"
set wildmode=list:longest,list:full
set wildignore+=*/__pycache__/*,*/venv/*,*/dist/*,*/node_modules/*

" List my marks"
nnoremap <Leader>m :marks abcdefghijklmnopqrstuvwxyz<CR>:normal! `

" Faster way to switch between buffers"
map <Leader>b :ls<CR>:b<Space>
map <Leader>` :buffer #<cr>

" From TPA's advanced motions P1, paste register stays unchanged "
xnoremap <Leader>p "_dP

" subtitutions made easier"
nnoremap <leader>s :%s/

" Fuzzy search files by name"
nnoremap <Leader>e :e **/*

" Place the cursor to the center of the screen for vertical movement and
" searches"
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv

" Add a new line in normal mode"
nnoremap <Leader>o o<Esc>k
nnoremap <Leader>O O<Esc>j

" Split window"
nnoremap so :split<Return><C-w>w
nnoremap se :vsplit<Return><C-w>w
" Resize window"
"nnoremap s<Left> <C-w><
"nnoremap s<Right> <C-w>>
"nnoremap s<Up> <C-w>+
"nnoremap s<Down> <C-w>-

" Move between split windows"
" nnoremap sh <C-w>h
" nnoremap sk <C-w>k
" nnoremap sl <C-w>l
" nnoremap sj <C-w>j

" Maximize window in a new tab"
nnoremap sm :tab split<CR>

" :W and :Q behave like :w and :q respectively "
command! W write
command! Q quit

" Create the tags file (may need to install ctags first)"
command! MakeTags !ctags -R .

" snippets"
nnoremap ,html :-1read $HOME/.vim/snippets/.skeleton.html<CR>4jf>a
nnoremap ,lorem :-1read $HOME/.vim/snippets/.lorem.txt<CR>
